export const pathname = {
	LOGIN: '/',
	GENERIC_COMPONENTS: '/components',
	FORGOT_PASSWORD: '/forgot-password',
	VALIDATE_OTP: '/validate-otp',
	SLM_ADMIN: '/slm-admin/dashboard',
	USER_MANAGEMENT: '/slm-admin/dashboard/user-management',
	ADD_TENANT: '/slm-admin/dashboard/user-management/add-tenant',
	HELP_DESK: '/slm-admin/dashboard/help-desk',
	VIEW_TICKET: '/slm-admin/dashboard/help-desk/view-ticket',
	VIEW_REPORT: '/slm-admin/dashboard/help-desk/view-report',
	TRANSACTION_HISTORY: '/slm-admin/dashboard/transaction-history',
	TRANSACTION_DETAILS: '/slm-admin/dashboard/transaction-history/:id',
	CONTENT_MANAGEMENT: '/slm-admin/dashboard/content-management',
	USER_DETAIL: '/slm-admin/dashboard/user-management/user-detail',
	HOSTELS: 'slm-admin/dashboard/hostels-management',
	ROOMS: 'slm-admin/dashboard/rooms-management',
	REPORTS: 'slm-admin/dashboard/reports',
};
