export const rowData = [
	{
		sl_no: 1,
		request_id: 'REQ001',
		name: 'John Doe',
		date: '2023-11-28',
		query: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
		attachment: 'file1.pdf',
		country: 'USA',
	},
	{
		sl_no: 2,
		request_id: 'REQ002',
		name: 'Jane Smith',
		date: '2023-11-29',
		query: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
		attachment: 'file2.docx',
		country: 'Canada',
	},
	{
		sl_no: 3,
		request_id: 'REQ003',
		name: 'Bob Johnson',
		date: '2023-11-30',
		query: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.',
		attachment: 'file3.jpg',
		country: 'UK',
	},
	{
		sl_no: 4,
		request_id: 'REQ004',
		name: 'Alice Brown',
		date: '2023-12-01',
		query: 'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.',
		attachment: 'file4.txt',
		country: 'Australia',
	},
	{
		sl_no: 5,
		request_id: 'REQ005',
		name: 'Charlie Wilson',
		date: '2023-12-02',
		query: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.',
		attachment: 'file5.png',
		country: 'New Zealand',
	},
	{
		sl_no: 6,
		request_id: 'REQ006',
		name: 'Eva Garcia',
		date: '2023-12-03',
		query: 'Sunt in culpa qui officia deserunt mollit anim id est laborum.',
		attachment: 'file6.doc',
		country: 'Spain',
	},
	{
		sl_no: 7,
		request_id: 'REQ007',
		name: 'David Lee',
		date: '2023-12-04',
		query: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
		attachment: 'file7.xlsx',
		country: 'South Korea',
	},
	{
		sl_no: 8,
		request_id: 'REQ008',
		name: 'Grace Miller',
		date: '2023-12-05',
		query: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
		attachment: 'file8.pdf',
		country: 'Germany',
	},
];
export const fakeData = [
	{ sl_no: 1, name: 'John Doe', country: 'USA', no_of_reports: 5, Reason: 'Excellent performance' },
	{ sl_no: 2, name: 'Jane Smith', country: 'Canada', no_of_reports: 8, Reason: 'Timely completion' },
	{ sl_no: 3, name: 'Bob Johnson', country: 'UK', no_of_reports: 3, Reason: 'Attention to detail' },
	{ sl_no: 4, name: 'Alice Williams', country: 'Australia', no_of_reports: 6, Reason: 'Problem-solving skills' },
	{ sl_no: 5, name: 'Michael Brown', country: 'USA', no_of_reports: 4, Reason: 'Team collaboration' },
	{ sl_no: 6, name: 'Sophia Davis', country: 'Germany', no_of_reports: 7, Reason: 'Innovative ideas' },
	{ sl_no: 7, name: 'David Wilson', country: 'Canada', no_of_reports: 2, Reason: 'Communication skills' },
	{ sl_no: 8, name: 'Olivia Miller', country: 'France', no_of_reports: 9, Reason: 'Leadership qualities' },
	{ sl_no: 9, name: 'Ethan Smith', country: 'USA', no_of_reports: 5, Reason: 'Adaptability' },
	{ sl_no: 10, name: 'Ava Johnson', country: 'Australia', no_of_reports: 6, Reason: 'Problem-solving skills' },
];
