// export let state = {
// 	loading: true,
// 	error: '',
// 	pathIcon: {},
// 	title: '',
// 	isLoading: false,
// 	isError: false,
// 	error: '',
// 	allActiveSessions: [],
// 	userName: null,
// 	showUser: false,
// 	customerId: null,
// 	intiateSessionData: {},
// 	stopTransactionData: {},
// 	statusError: false,
// 	count: null,
// 	countInAccount: null,
// 	customerCount: null,
// 	getUserDetails: [],
// 	getUserChargingTransaction: [],
// 	showUser: false,
// 	isErrorInFetch: false,
// };

// export default state;
